name: api_env
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=1.3.0=py38_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - cffi=1.14.0=py38hb5b8e2f_0
  - click=7.0=py_0
  - cryptography=2.8=py38ha12b0ac_0
  - flask=1.1.1=py_0
  - flask-jwt-extended=3.20.0=py_0
  - flask-sqlalchemy=2.4.0=py_0
  - idna=2.8=py38_1000
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.1=py_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - markupsafe=1.1.1=py38h1de35cc_0
  - ncurses=6.2=h0a44026_0
  - openssl=1.1.1d=h1de35cc_4
  - pip=20.0.2=py38_1
  - pycparser=2.19=py_0
  - pyjwt=1.7.1=py38_0
  - python=3.8.1=h359304d_1
  - python_abi=3.8=1_cp38
  - readline=7.0=h1de35cc_5
  - setuptools=46.0.0=py38_0
  - six=1.14.0=py38_0
  - sqlalchemy=1.3.16=py38h64e0658_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - aniso8601==8.0.0
    - attrs==19.3.0
    - flask-restx==0.1.1
    - flask-script==2.0.6
    - jsonschema==3.2.0
    - mongoengine==0.19.1
    - pymongo==3.10.1
    - pyrsistent==0.15.7
    - pytz==2019.3
    - werkzeug==0.16.1

